language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm

env:
  - DB=mysql
  - DB=sqlite
  - DB=postgres

matrix:
  # hhvm doesn't support postgres currently
  allow_failures:
    - php: hhvm
      env: DB=postgres
  fast_finish: true

before_script: sh tests/travis/before.sh

script: phpunit --configuration tests/travis/$DB/phpunit.xml

sudo: false
